services:
  95598-mqtt:
    image: ghcr.io/goxofy/95598-mqtt:main
    container_name: 95598-mqtt
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./errors:/app/errors
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    #如果报 pthread_create error, 可以尝试取消下面两行注释
    # security_opt:
    #   - seccomp:unconfined
